# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b111cff0b16fc130ca4bd5a41fcea1cce335aec78a99fc0160c3fd17bc95e13b5b355aa63d748a615a5a95e59c65353d40a07284bcc85fa59beb40462efa880

test:
  secret_key_base: 7b3d837701b75269367a0457bcc64f62f1147099e80fead9de0e564f8f9985e54dec5597f18908385932486fbc991d9d22190e3a58c6e13f1f44222cd7b3a032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
